language: php

php:
 - 7.0.10

branches:
 - master

before_script:
 - phpenv config-rm xdebug.ini
 - mkdir plugins
 - wget -O plugins/DevTools.phar https://raw.githubusercontent.com/PrismarineMC/Prismarine/master/DevTools.phar
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC8

script:
 - php build.php
